version: "3.8"

# Definimos una red explícita para que todos los servicios hablen el mismo idioma
networks:
  monitoring-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    build:
      context: .
      dockerfile: prometheus.dockerfile
    ports:
      - "19090:9090"
    container_name: prometheus_service
    volumes:
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    networks:
      - monitoring-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor_service
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    restart: unless-stopped
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_service
    ports:
      - "13000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring-net

  # --- AÑADIMOS EL NUEVO SERVICIO NODE-EXPORTER ---
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_service
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/host"
    pid: "host" # Esencial para que pueda leer los procesos del host
    restart: unless-stopped
    networks: # Lo conectamos a la misma red
      - monitoring-net
