global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # --- AÑADIMOS EL NUEVO JOB PARA NODE-EXPORTER ---
  - job_name: "node-exporter"
    static_configs:
      # El puerto por defecto de node-exporter es el 9100
      - targets: ["node-exporter:9100"]
